name: Dotrix Website Test and Build

on:
  push:
    branches: [ main, staging ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Install SSH Key
      uses: lowenware/ssh-key-action@v2
      with:
        key: ${{ secrets.DOTRIX_WEBSITE_SSH }}
        known_hosts: 'dotrix-host'
    - name: Add Known Hosts
      run: ssh-keyscan -H ${{ secrets.DOTRIX_SSH_HOST }} >> ~/.ssh/known_hosts
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build:export
    - name: Upload
      run: rsync -avz ./out/ ${{ secrets.DOTRIX_SSH_USER }}@${{ secrets.DOTRIX_SSH_HOST }}:/srv/${{ secrets.DOTRIX_SSH_USER }}/${{ github.ref_name }}/

